### ISSUE TITLE
Add configuration about linked item resolver

### ISSUE THREAD

**Issue by xuopled** [contentful/contentful.js#119]
Hi, it could be great to configure how to resolve a linked item automatically.
For example, if an item has an `author` field which references an `author` item, I want it to be resolve as author name.

```
var contentful = require('contentful')
var client = contentful.createClient({
  space: mySpace,
  accessToken: myAccessToke,
})
client.getEntry(id, {
  // here is the config
  resolveConfig: {
    author: name
  }
})
.then((entry) => console.log(entry))
```

For some static site generator, it could be very usefull because we need to request pure data to generate markdown files. So get refs is not usefull.

Configuration could be great to avoid these hacks : 
```
const {body, ...fields} = post.fields
const frontmatter = {
  ...fields,
  ...fields.author && {author: fields.author.map(author => author.fields.name)},
  ...fields.category && {category: fields.category.map(category => category.fields.title)},
  ...fields.featuredImage && {featuredImage: fields.featuredImage.fields.file.url},
}
createMarkdown(body, frontmatter)
```

**Comment by Khaledgarbaya** [comment]
@xuopled ,
The link resolution is included in the SDK, you just need to use the collection endpoint instead.
So the code should be 

```javascript
var contentful = require('contentful')
var client = contentful.createClient({
  space: mySpace,
  accessToken: myAccessToke,
})
client.getEntries({'sys.id': 'entryId'})
.then((response) => console.log(response.items[0]))
```
link resolution only happens when requesting the collection endpoint. because the SDK will have acces to the linked entries and can resolve them for you, the linking can be up to 10 levels deep and you control that if you send `include` param , by default it is 1.

Example using `include`
```javascript
var contentful = require('contentful')
var client = contentful.createClient({
  space: mySpace,
  accessToken: myAccessToke,
})
client.getEntries({'sys.id': 'entryId', 'include': 5}) // 5 level deep links
.then((re

**Comment by xuopled** [comment]
I think you don't understand my need : 

I don't want to get the whole author object if I request the post : 

```
title: Down the Rabbit Hole
slug: down-the-rabbit-hole
author:
  - &ref_0
    sys:
      space:
        sys:
          type: Link
          linkType: Space
          id: wdrlqiaj0bs4
      id: 6EczfGnuHCIYGGwEwIqiq2
      type: Entry
      createdAt: '2017-02-19T12:17:13.390Z'
      updatedAt: '2017-02-19T12:17:13.390Z'
      revision: 1
      contentType:
        sys:
          type: Link
          linkType: ContentType
          id: 1kUEViTN4EmGiEaaeC6ouY
      locale: fr-FR
    fields:
      name: Lewis Carroll
      website: 'http://en.wikipedia.org/wiki/Lewis_Carroll'
      profilePhoto:
        sys:
          space:
            sys:
```

I need a specific information, for example the author name : 

```
title: Down the Rabbit Hole
slug: down-the-rabbit-hole
author: Lewis Carroll
```
